/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitCommitWorktreeIdPostRequest {
    #[serde(rename = "message")]
    pub message: String,
}

impl GitCommitWorktreeIdPostRequest {
    pub fn new(message: String) -> GitCommitWorktreeIdPostRequest {
        GitCommitWorktreeIdPostRequest { message }
    }
}
