/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActiveStrategy : Represents the globally active strategy and optional focus task groups.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActiveStrategy {
    #[serde(rename = "id")]
    pub id: models::Strategy,
    /// Optional list of task group identifiers receiving additional focus.
    #[serde(rename = "focus", skip_serializing_if = "Option::is_none")]
    pub focus: Option<Vec<i64>>,
}

impl ActiveStrategy {
    /// Represents the globally active strategy and optional focus task groups.
    pub fn new(id: models::Strategy) -> ActiveStrategy {
        ActiveStrategy { id, focus: None }
    }
}
