/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentReasoningOverrides : Reasoning effort per persona. When a persona is configured to use gpt-5.1-codex-mini, the \"low\" reasoning level is not supported.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentReasoningOverrides {
    #[serde(rename = "orchestrator")]
    pub orchestrator: models::ReasoningEffort,
    #[serde(rename = "worker")]
    pub worker: models::ReasoningEffort,
    #[serde(rename = "wizard")]
    pub wizard: models::ReasoningEffort,
}

impl AgentReasoningOverrides {
    /// Reasoning effort per persona. When a persona is configured to use gpt-5.1-codex-mini, the \"low\" reasoning level is not supported.
    pub fn new(orchestrator: models::ReasoningEffort, worker: models::ReasoningEffort, wizard: models::ReasoningEffort) -> AgentReasoningOverrides {
        AgentReasoningOverrides {
            orchestrator,
            worker,
            wizard,
        }
    }
}

