/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AgentModelOverrides : Model selection per persona.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentModelOverrides {
    /// Codex model used for the orchestrator persona.
    #[serde(rename = "orchestrator")]
    pub orchestrator: Orchestrator,
    /// Codex model used for worker personas.
    #[serde(rename = "worker")]
    pub worker: Worker,
    /// Codex model used by the task wizard helper.
    #[serde(rename = "wizard")]
    pub wizard: Wizard,
}

impl AgentModelOverrides {
    /// Model selection per persona.
    pub fn new(orchestrator: Orchestrator, worker: Worker, wizard: Wizard) -> AgentModelOverrides {
        AgentModelOverrides {
            orchestrator,
            worker,
            wizard,
        }
    }
}
/// Codex model used for the orchestrator persona.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Orchestrator {
    #[serde(rename = "gpt-5.1-codex-max")]
    Gpt5Period1CodexMax,
    #[serde(rename = "gpt-5.1-codex")]
    Gpt5Period1Codex,
    #[serde(rename = "gpt-5.1-codex-mini")]
    Gpt5Period1CodexMini,
    #[serde(rename = "gpt-5.1")]
    Gpt5Period1,
}

impl Default for Orchestrator {
    fn default() -> Orchestrator {
        Self::Gpt5Period1CodexMax
    }
}
/// Codex model used for worker personas.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Worker {
    #[serde(rename = "gpt-5.1-codex-max")]
    Gpt5Period1CodexMax,
    #[serde(rename = "gpt-5.1-codex")]
    Gpt5Period1Codex,
    #[serde(rename = "gpt-5.1-codex-mini")]
    Gpt5Period1CodexMini,
    #[serde(rename = "gpt-5.1")]
    Gpt5Period1,
}

impl Default for Worker {
    fn default() -> Worker {
        Self::Gpt5Period1CodexMax
    }
}
/// Codex model used by the task wizard helper.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Wizard {
    #[serde(rename = "gpt-5.1-codex-max")]
    Gpt5Period1CodexMax,
    #[serde(rename = "gpt-5.1-codex")]
    Gpt5Period1Codex,
    #[serde(rename = "gpt-5.1-codex-mini")]
    Gpt5Period1CodexMini,
    #[serde(rename = "gpt-5.1")]
    Gpt5Period1,
}

impl Default for Wizard {
    fn default() -> Wizard {
        Self::Gpt5Period1CodexMax
    }
}

