/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AppendFilesConfig : Append-file settings for orchestrator and worker roles.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppendFilesConfig {
    /// List of file paths appended to orchestrator prompts.
    #[serde(rename = "orchestrator")]
    pub orchestrator: Vec<String>,
    /// List of file paths appended to worker prompts.
    #[serde(rename = "worker")]
    pub worker: Vec<String>,
}

impl AppendFilesConfig {
    /// Append-file settings for orchestrator and worker roles.
    pub fn new(orchestrator: Vec<String>, worker: Vec<String>) -> AppendFilesConfig {
        AppendFilesConfig {
            orchestrator,
            worker,
        }
    }
}
