/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CommandConfig : Declarative command configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommandConfig {
    #[serde(rename = "id")]
    pub id: String,
    /// Shell command and arguments to execute.
    #[serde(rename = "exec")]
    pub exec: Vec<String>,
    #[serde(rename = "stdout_success_message", skip_serializing_if = "Option::is_none")]
    pub stdout_success_message: Option<String>,
    #[serde(rename = "hidden", skip_serializing_if = "Option::is_none")]
    pub hidden: Option<bool>,
    #[serde(rename = "timeout_seconds", skip_serializing_if = "Option::is_none")]
    pub timeout_seconds: Option<i64>,
    /// Override working directory for this command. Paths may be absolute or relative to the workspace root.
    #[serde(rename = "cwd", skip_serializing_if = "Option::is_none")]
    pub cwd: Option<String>,
}

impl CommandConfig {
    /// Declarative command configuration.
    pub fn new(id: String, exec: Vec<String>) -> CommandConfig {
        CommandConfig {
            id,
            exec,
            stdout_success_message: None,
            hidden: None,
            timeout_seconds: None,
            cwd: None,
        }
    }
}

