/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CommitInfo : Metadata about a task's tracked commit.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommitInfo {
    /// Full commit hash.
    #[serde(rename = "hash")]
    pub hash: String,
    /// Commit message.
    #[serde(rename = "message")]
    pub message: String,
    /// Output of `git diff --stat {hash}^!`.
    #[serde(rename = "diff")]
    pub diff: String,
}

impl CommitInfo {
    /// Metadata about a task's tracked commit.
    pub fn new(hash: String, message: String, diff: String) -> CommitInfo {
        CommitInfo {
            hash,
            message,
            diff,
        }
    }
}
