/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Config : Workspace configuration stored on disk.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Config {
    /// Absolute path of the workspace the server is running in.
    #[serde(rename = "workspace_path", skip_serializing_if = "Option::is_none")]
    pub workspace_path: Option<String>,
    #[serde(rename = "append_agents_file")]
    pub append_agents_file: Box<models::AppendFilesConfig>,
    #[serde(rename = "models")]
    pub models: Box<models::AgentModelOverrides>,
    #[serde(rename = "reasoning")]
    pub reasoning: Box<models::AgentReasoningOverrides>,
    #[serde(rename = "commands")]
    pub commands: Vec<models::CommandConfig>,
    /// Commands executed after each turn.
    #[serde(rename = "post_turn_checks")]
    pub post_turn_checks: Vec<String>,
    #[serde(rename = "docker_overrides")]
    pub docker_overrides: Box<models::DockerOverrides>,
    /// Action to take when staging worktree is dirty during task completion.
    #[serde(
        rename = "dirty_staging_action",
        skip_serializing_if = "Option::is_none"
    )]
    pub dirty_staging_action: Option<String>,
    /// Commands to execute when staging is updated.
    #[serde(
        rename = "on_staging_change",
        skip_serializing_if = "Option::is_none"
    )]
    pub on_staging_change: Option<Vec<String>>,
}

impl Config {
    /// Workspace configuration stored on disk.
    pub fn new(append_agents_file: models::AppendFilesConfig, models: models::AgentModelOverrides, reasoning: models::AgentReasoningOverrides, commands: Vec<models::CommandConfig>, post_turn_checks: Vec<String>, docker_overrides: models::DockerOverrides) -> Config {
        Config {
            workspace_path: None,
            append_agents_file: Box::new(append_agents_file),
            models: Box::new(models),
            reasoning: Box::new(reasoning),
            commands,
            post_turn_checks,
            docker_overrides: Box::new(docker_overrides),
            dirty_staging_action: None,
            on_staging_change: None,
        }
    }
}
