/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// DockerOverrides : Additional docker args injected before the image per persona.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DockerOverrides {
    #[serde(rename = "orchestrator", default)]
    pub orchestrator: Vec<String>,
    #[serde(rename = "worker", default)]
    pub worker: Vec<String>,
    #[serde(rename = "wizard", default)]
    pub wizard: Vec<String>,
}

impl DockerOverrides {
    /// Additional docker args injected before the image per persona.
    pub fn new(
        orchestrator: Vec<String>,
        worker: Vec<String>,
        wizard: Vec<String>,
    ) -> DockerOverrides {
        DockerOverrides {
            orchestrator,
            worker,
            wizard,
        }
    }
}
