/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExecCommandInput : Request payload for executing a shell command.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecCommandInput {
    #[serde(rename = "command")]
    pub command: String,
    /// Optional working directory override relative to the workspace root.
    #[serde(rename = "cwd", skip_serializing_if = "Option::is_none")]
    pub cwd: Option<String>,
}

impl ExecCommandInput {
    /// Request payload for executing a shell command.
    pub fn new(command: String) -> ExecCommandInput {
        ExecCommandInput { command, cwd: None }
    }
}
