/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Feed : Feed entry emitted by system components.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Feed {
    #[serde(rename = "id")]
    pub id: i64,
    /// Emitter of the feed entry (Orchestrator, Quality Assurance, System, ws#).
    #[serde(rename = "source")]
    pub source: String,
    /// Recipient focus (Orchestrator, Quality Assurance, System, ws#).
    #[serde(rename = "target")]
    pub target: String,
    /// Unix timestamp in seconds.
    #[serde(rename = "ts")]
    pub ts: i64,
    #[serde(rename = "level")]
    pub level: models::FeedLevel,
    /// Human-friendly summary.
    #[serde(rename = "text")]
    pub text: String,
    /// Raw log payload.
    #[serde(rename = "raw")]
    pub raw: String,
    /// Category tag for the entry.
    #[serde(rename = "category")]
    pub category: String,
}

impl Feed {
    /// Feed entry emitted by system components.
    pub fn new(id: i64, source: String, target: String, ts: i64, level: models::FeedLevel, text: String, raw: String, category: String) -> Feed {
        Feed {
            id,
            source,
            target,
            ts,
            level,
            text,
            raw,
            category,
        }
    }
}

