/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FeedOrderField : Valid Feed fields that can be used for ordering.
/// Valid Feed fields that can be used for ordering.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FeedOrderField {
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "source")]
    Source,
    #[serde(rename = "target")]
    Target,
    #[serde(rename = "ts")]
    Ts,
    #[serde(rename = "level")]
    Level,
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "raw")]
    Raw,
    #[serde(rename = "category")]
    Category,
}

impl std::fmt::Display for FeedOrderField {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Id => write!(f, "id"),
            Self::Source => write!(f, "source"),
            Self::Target => write!(f, "target"),
            Self::Ts => write!(f, "ts"),
            Self::Level => write!(f, "level"),
            Self::Text => write!(f, "text"),
            Self::Raw => write!(f, "raw"),
            Self::Category => write!(f, "category"),
        }
    }
}

impl Default for FeedOrderField {
    fn default() -> FeedOrderField {
        Self::Id
    }
}
