/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetHealthz200Response {
    /// Indicates the server is running.
    #[serde(rename = "status")]
    pub status: String,
}

impl GetHealthz200Response {
    pub fn new(status: String) -> GetHealthz200Response {
        GetHealthz200Response {
            status,
        }
    }
}

