/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GitWorktreeStatus : Git status data for a single worktree.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitWorktreeStatus {
    /// Logical identifier (staging or ws{n}).
    #[serde(rename = "id")]
    pub id: String,
    /// Absolute filesystem path to the worktree.
    #[serde(rename = "path")]
    pub path: String,
    /// Currently checked out branch.
    #[serde(rename = "branch")]
    pub branch: String,
    /// Configured upstream tracking branch, if any.
    #[serde(rename = "upstream", skip_serializing_if = "Option::is_none")]
    pub upstream: Option<String>,
    /// Number of commits ahead of upstream.
    #[serde(rename = "ahead")]
    pub ahead: i32,
    /// Number of commits behind upstream.
    #[serde(rename = "behind")]
    pub behind: i32,
    /// True when there are local modifications.
    #[serde(rename = "is_dirty")]
    pub is_dirty: bool,
    /// Per-file change metadata.
    #[serde(rename = "files")]
    pub files: Vec<models::GitStatusFileChange>,
}

impl GitWorktreeStatus {
    /// Git status data for a single worktree.
    pub fn new(
        id: String,
        path: String,
        branch: String,
        ahead: i32,
        behind: i32,
        is_dirty: bool,
        files: Vec<models::GitStatusFileChange>,
    ) -> GitWorktreeStatus {
        GitWorktreeStatus {
            id,
            path,
            branch,
            upstream: None,
            ahead,
            behind,
            is_dirty,
            files,
        }
    }
}
