/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GitStatusSummary : Aggregated git status for every discovered worktree.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitStatusSummary {
    #[serde(rename = "worktrees")]
    pub worktrees: Vec<models::GitWorktreeStatus>,
}

impl GitStatusSummary {
    /// Aggregated git status for every discovered worktree.
    pub fn new(worktrees: Vec<models::GitWorktreeStatus>) -> GitStatusSummary {
        GitStatusSummary { worktrees }
    }
}
