/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GitStatusHunk : Single diff hunk extracted from git output.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitStatusHunk {
    /// The @@ header line describing the hunk range.
    #[serde(rename = "header")]
    pub header: String,
    /// All lines within the hunk including +/- context.
    #[serde(rename = "lines")]
    pub lines: Vec<String>,
}

impl GitStatusHunk {
    /// Single diff hunk extracted from git output.
    pub fn new(header: String, lines: Vec<String>) -> GitStatusHunk {
        GitStatusHunk { header, lines }
    }
}
