/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GitStatusFileChange : Represents a single file appearing in git status output.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GitStatusFileChange {
    /// Current file path relative to the worktree root.
    #[serde(rename = "path")]
    pub path: String,
    /// Previous path when the file was renamed or moved.
    #[serde(rename = "old_path", skip_serializing_if = "Option::is_none")]
    pub old_path: Option<String>,
    /// Two-character porcelain status code (e.g., M?, R?).
    #[serde(rename = "status_code")]
    pub status_code: String,
    /// Number of added lines reported by git.
    #[serde(rename = "additions")]
    pub additions: i32,
    /// Number of removed lines reported by git.
    #[serde(rename = "deletions")]
    pub deletions: i32,
    /// Diff hunks for this file when requested.
    #[serde(rename = "hunks", skip_serializing_if = "Option::is_none")]
    pub hunks: Option<Vec<models::GitStatusHunk>>,
}

impl GitStatusFileChange {
    /// Represents a single file appearing in git status output.
    pub fn new(path: String, status_code: String, additions: i32, deletions: i32) -> GitStatusFileChange {
        GitStatusFileChange {
            path,
            old_path: None,
            status_code,
            additions,
            deletions,
            hunks: None,
        }
    }
}

