/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InsertMessageOneOf1 {
    #[serde(rename = "after")]
    pub after: i64,
}

impl InsertMessageOneOf1 {
    pub fn new(after: i64) -> InsertMessageOneOf1 {
        InsertMessageOneOf1 {
            after,
        }
    }
}

