/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InsertMessage : Directive for inserting a message relative to another message id.
/// Directive for inserting a message relative to another message id.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum InsertMessage {
    InsertMessageOneOf(Box<models::InsertMessageOneOf>),
    InsertMessageOneOf1(Box<models::InsertMessageOneOf1>),
}

impl Default for InsertMessage {
    fn default() -> Self {
        Self::InsertMessageOneOf(Default::default())
    }
}

