/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Message : Represents a queued message between agents.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Message {
    #[serde(rename = "id")]
    pub id: i64,
    /// Message sender or recipient display value (\"Orchestrator\", \"Quality Assurance\", or worker handles like \"ws42\").
    #[serde(rename = "from")]
    pub from: String,
    /// Message sender or recipient display value (\"Orchestrator\", \"Quality Assurance\", or worker handles like \"ws42\").
    #[serde(rename = "to")]
    pub to: String,
    #[serde(rename = "message")]
    pub message: String,
    /// Unix timestamp (seconds) when the message was queued.
    #[serde(rename = "inserted_at")]
    pub inserted_at: i64,
}

impl Message {
    /// Represents a queued message between agents.
    pub fn new(id: i64, from: String, to: String, message: String, inserted_at: i64) -> Message {
        Message {
            id,
            from,
            to,
            message,
            inserted_at,
        }
    }
}

