/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageEnqueueInput {
    /// Message sender or recipient display value (\"Orchestrator\", \"Quality Assurance\", or worker handles like \"ws42\").
    #[serde(rename = "from")]
    pub from: String,
    /// Message sender or recipient display value (\"Orchestrator\", \"Quality Assurance\", or worker handles like \"ws42\").
    #[serde(rename = "to")]
    pub to: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl MessageEnqueueInput {
    pub fn new(from: String, to: String, message: String) -> MessageEnqueueInput {
        MessageEnqueueInput { from, to, message }
    }
}
