/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueueState {
    #[serde(rename = "paused")]
    pub paused: bool,
}

impl QueueState {
    pub fn new(paused: bool) -> QueueState {
        QueueState {
            paused,
        }
    }
}

