/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Strategy : System-wide execution strategy.
/// System-wide execution strategy.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Strategy {
    #[serde(rename = "AGGRESSIVE")]
    Aggressive,
    #[serde(rename = "MODERATE")]
    Moderate,
    #[serde(rename = "ECONOMICAL")]
    Economical,
    #[serde(rename = "BUG_SMASH")]
    BugSmash,
    #[serde(rename = "HOTFIX_SWARM")]
    HotfixSwarm,
    #[serde(rename = "PLANNING")]
    Planning,
    #[serde(rename = "WIND_DOWN")]
    WindDown,
}

impl std::fmt::Display for Strategy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Aggressive => write!(f, "AGGRESSIVE"),
            Self::Moderate => write!(f, "MODERATE"),
            Self::Economical => write!(f, "ECONOMICAL"),
            Self::BugSmash => write!(f, "BUG_SMASH"),
            Self::HotfixSwarm => write!(f, "HOTFIX_SWARM"),
            Self::Planning => write!(f, "PLANNING"),
            Self::WindDown => write!(f, "WIND_DOWN"),
        }
    }
}

impl Default for Strategy {
    fn default() -> Strategy {
        Self::Aggressive
    }
}
