/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TaskCreateInput : Payload for creating a task.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskCreateInput {
    #[serde(rename = "group_id")]
    pub group_id: i64,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "title")]
    pub title: String,
    /// Commit hash associated with the task.
    #[serde(rename = "commit_hash", skip_serializing_if = "Option::is_none")]
    pub commit_hash: Option<String>,
    #[serde(rename = "status")]
    pub status: models::TaskStatus,
    /// Owner information encoded as display text (\"Orchestrator\", \"Quality Assurance\", or worker handles like \"ws42\").
    #[serde(rename = "owner")]
    pub owner: String,
    /// Detailed description of the task.
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "model_override", skip_serializing_if = "Option::is_none")]
    pub model_override: Option<String>,
    #[serde(rename = "reasoning_override", skip_serializing_if = "Option::is_none")]
    pub reasoning_override: Option<String>,
}

impl TaskCreateInput {
    /// Payload for creating a task.
    pub fn new(group_id: i64, slug: String, title: String, status: models::TaskStatus, owner: String, description: String) -> TaskCreateInput {
        TaskCreateInput {
            group_id,
            slug,
            title,
            commit_hash: None,
            status,
            owner,
            description,
            model_override: None,
            reasoning_override: None,
        }
    }
}

