/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TaskGroupUpdateInput : Payload for updating mutable task group fields. Status cannot be modified directly.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskGroupUpdateInput {
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl TaskGroupUpdateInput {
    /// Payload for updating mutable task group fields. Status cannot be modified directly.
    pub fn new() -> TaskGroupUpdateInput {
        TaskGroupUpdateInput {
            slug: None,
            title: None,
            description: None,
        }
    }
}

