/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TaskDependencyCreateInput : Payload for creating a dependency between two tasks.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskDependencyCreateInput {
    #[serde(rename = "task_id")]
    pub task_id: i64,
    #[serde(rename = "depends_on_task_id")]
    pub depends_on_task_id: i64,
}

impl TaskDependencyCreateInput {
    /// Payload for creating a dependency between two tasks.
    pub fn new(task_id: i64, depends_on_task_id: i64) -> TaskDependencyCreateInput {
        TaskDependencyCreateInput {
            task_id,
            depends_on_task_id,
        }
    }
}

