/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TaskGroupCreateInput : Payload for creating a task group. Status is derived automatically.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskGroupCreateInput {
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description")]
    pub description: String,
}

impl TaskGroupCreateInput {
    /// Payload for creating a task group. Status is derived automatically.
    pub fn new(slug: String, title: String, description: String) -> TaskGroupCreateInput {
        TaskGroupCreateInput {
            slug,
            title,
            description,
        }
    }
}

