/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TaskGroup : Task grouping metadata with derived status.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskGroup {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "status")]
    pub status: models::TaskGroupStatus,
}

impl TaskGroup {
    /// Task grouping metadata with derived status.
    pub fn new(
        id: i64,
        slug: String,
        title: String,
        description: String,
        status: models::TaskGroupStatus,
    ) -> TaskGroup {
        TaskGroup {
            id,
            slug,
            title,
            description,
            status,
        }
    }
}
