/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TaskStatus : High-level state for a task.
/// High-level state for a task.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TaskStatus {
    #[serde(rename = "Ready")]
    Ready,
    #[serde(rename = "Blocked")]
    Blocked,
    #[serde(rename = "Done")]
    Done,
}

impl std::fmt::Display for TaskStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ready => write!(f, "Ready"),
            Self::Blocked => write!(f, "Blocked"),
            Self::Done => write!(f, "Done"),
        }
    }
}

impl Default for TaskStatus {
    fn default() -> TaskStatus {
        Self::Ready
    }
}
