/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TaskDependency : Represents a dependency relationship where a task depends on another task.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskDependency {
    #[serde(rename = "task_id")]
    pub task_id: i64,
    #[serde(rename = "depends_on_task_id")]
    pub depends_on_task_id: i64,
}

impl TaskDependency {
    /// Represents a dependency relationship where a task depends on another task.
    pub fn new(task_id: i64, depends_on_task_id: i64) -> TaskDependency {
        TaskDependency {
            task_id,
            depends_on_task_id,
        }
    }
}

