/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TaskGroupStatus : Derived status for a task group: Done when it has no tasks or every task is Done, otherwise Ready.
/// Derived status for a task group: Done when it has no tasks or every task is Done, otherwise Ready.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TaskGroupStatus {
    #[serde(rename = "Ready")]
    Ready,
    #[serde(rename = "Done")]
    Done,

}

impl std::fmt::Display for TaskGroupStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ready => write!(f, "Ready"),
            Self::Done => write!(f, "Done"),
        }
    }
}

impl Default for TaskGroupStatus {
    fn default() -> TaskGroupStatus {
        Self::Ready
    }
}

