/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Worker : Worker metadata.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Worker {
    #[serde(rename = "id")]
    pub id: i64,
    /// Unix timestamp in seconds when the worker last reported.
    #[serde(rename = "last_seen")]
    pub last_seen: i64,
    #[serde(rename = "state")]
    pub state: models::WorkerState,
}

impl Worker {
    /// Worker metadata.
    pub fn new(id: i64, last_seen: i64, state: models::WorkerState) -> Worker {
        Worker {
            id,
            last_seen,
            state,
        }
    }
}

