/*
 * Robot Farm API
 *
 * Base OpenAPI definition for Robot Farm services.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkerState : State reported by the worker.
/// State reported by the worker.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WorkerState {
    #[serde(rename = "Ready")]
    Ready,
    #[serde(rename = "Working")]
    Working,
    #[serde(rename = "Blocked")]
    Blocked,
    #[serde(rename = "Done")]
    Done,
}

impl std::fmt::Display for WorkerState {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ready => write!(f, "Ready"),
            Self::Working => write!(f, "Working"),
            Self::Blocked => write!(f, "Blocked"),
            Self::Done => write!(f, "Done"),
        }
    }
}

impl Default for WorkerState {
    fn default() -> WorkerState {
        Self::Ready
    }
}
